### ISSUE TITLE
Value set by Node-Red not accepted

### ISSUE THREAD

**Issue by tombenzeen** [iobroker-community-adapters/ioBroker.kecontact#10]
When i set the value kecontact.0.currentUser via the Admin Console the Value is accepted and the charge station will do their job When i set the Vlaue (also in mA) through node-red for example the Value will be changed after a sec to 6000 mA. Seems that not every source is accpeted.... Other values like kecontact.0.enableUser are working

**Comment by UncleSamSwiss** [comment]
Were you able to figure this out?
If not: did you send the value as an integer (e.g. 3000) or did you include "mA". A simple integer should work fine. In general setting any value (where writable) works exactly the same in this adapter, so my guess is, you have an error in your node-red configuration.

**Comment by Sneak-L8** [comment]
Hi, is this issue still pending? Many changes were made since then...

**Comment by Sneak-L8** [comment]
semms no longer to be open
