### ISSUE TITLE
Einbindung eines Speichers

### ISSUE THREAD

**Issue by matthiasisrael** [iobroker-community-adapters/ioBroker.kecontact#109]
Hallo,

ist es möglich den Adapter so zu erweitern, dass ein vorhandener Batteriespeicher mit berücksichtigt wird?

Konkret habe ich folgendes Problem:
Scheint die Sonne und die erzeugte Energie übersteigt die im Haus verbrauchte, wird zunächst unser BYD-Speicher geladen und dementsprechend kein (oder nur sehr wenig) Strom eingespeist. Ist der Speicher voll geladen steigt die eingespeiste Energie sprunghaft an und der Adapter startet den Ladevorgang. Soweit so gut :-)
Sinkt jetzt jedoch im Laufe des Ladevorgangs die Leistung der PV-Anlage (z.B. durch aufziehende Wolken) kompensiert der Speicher die fehlende Energiemenge und wird solange entladen, bis so wenig PV-Energie vorhanden ist, dass ein Netzbezug stattfindet. Dann wird der Ladevorgang unterbrochen.
Wünschenswert wären daher die Einbeziehung des Ladestandes (SOC) der Batterie und der Stromfluss von der Batterie zum WR, sodass der Speicher nicht (oder nicht unter eine bestimmte Schwelle wie z.B. 60%) entladen wird.
Ist ein solches Szenario umsetzbar?

Gruß
Matthias

**Comment by Sneak-L8** [comment]
Bitte mal die aktuelle v1.4.0 von github installieren. Da ist die Nutzung eines Speichers beim Adapter berücksichtigt. Da Auto lädt vorrangig vor der Batterie. Eine Entnahme aus dem Batteriespeicher ist noch nicht vorgesehen, wäre aber prinipiell möglich. Im Thread: https://forum.iobroker.net/topic/6343/frage-realisierung-adapter-udp-keba-wallbox wurde das auch schon diskutiert.

**Comment by matthiasisrael** [comment]
Eine Entnahme bis zu einer gewissen Grenze wäre in meinem Fall sinnvoll und toll, wenn das aufgenommen werden könnte.
Bei der v.1.4.0 funktioniert bei mir leider das PV-optimierte Laden nicht mehr. Es wird mit voller Leistung geladen. D.h. es wird sowohl der Speicher maximal entladen als auch aus dem Netz bezogen um auf meine max. 16A zu kommen.

**Comment by Sneak-L8** [comment]
Ich kann die Speichereinbindung leider nur im Blindflug machen, da ich selbsr keinen habe. Bitte sende mir mal die Konfiguration und wie sich der Wert im State für den Speicher ergibt.
Für die Funktion "Entnahme aus Speicher" bräuchte ich die Info, welche Daten vom Batteriespeicher bereitgestellt werden. Verügbare Leistung? Verfügbare Strommenge oder Ladezustand in % (SoC)?
Und dann zum Handling: ich tendiere dazu, die Steuerung nicht in die Konfig zu nehmen, sondern über state im channel "automatic" zu regeln. Dann kannst Du entweder einmalig Werte hinterlegen oder selbst per Script steuern, welchen Beitrag der Speicher beim Laden leisten soll.
Wenn es die o.g. WErte gibt, könnte man eine max. Leistung einstellen, die aus der Batterie entnommen werden darf und eine Untergrenze, die der Ladezustand Speicher nicht unterschreiten darf.
Diese Werte könntest Du dann z.B. in einem Skript je nach erwarteter Sonneneinstrahlung tagsüber auf 0 W begrenzen oder nur im Winter aktivieren, wenn sonst gar kein (Überschuiss-)Laden möglich wäre, weil die Sonne nicht genug Leistung bringt...

**Comment by matthiasisrael** [comment]
Hallo Sneak,bitte entschuldige die späte Antwort, ich bin derzeit unterwegs und kam daher nicht früher zu einer Antwort. Ich habe einen BYD Speicher, dessen Werte über den Fronius Adapter (über den WR) in den iobroker wandern. Fronius.0.powerflow.P_AkkuIst ein positiver Wert in Watt, wenn der Akku Energie abgibt und damit entladen wird und ein negativer Wert in Watt, wenn der Akku geladen wird. Diesen State habe ich in der Konfiguration der Instanz bei Akku eingetragen. Fronius.0.powerflow.inverter1.socGibt den Ladestand des Akkus in Prozent an.Das Regeln der Leistung über ein Script halte ich ebenfalls für sinnvoll. Gerade in den Wintermonaten wäre es super minimal mit 6A laden zu können und dies als State manuell oder per Script zu setzen.Wo müsste dieser Wert eingetragen werden? Vielen Dank für deine Mühe! GrußMatthiasVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Sneak-L8 ***@***.***> Datum: 20.05.22  22:13  (GMT+01:00) An: "iobroker-community-adapters/ioBroker.kecontact" ***@***.***> Cc: matthiasisrael ***@***.***>, Author ***@***.***> Betreff: Re: [iobroker-community-adapters/ioBroker.kecontact] Einbindung eines Speichers (Issue #109) 

Ich kann die Speichereinbindung leider nur im Blindflug machen, da ich selbsr keinen habe. Bitte sende mir mal die Konfiguration und wie sich der Wert im State für den Speicher ergibt.

Für die Funktion "Entnahme aus Speicher" bräuchte ich die Info, welche Daten vom Batteriespeicher bereitgestellt werden. Verügbare Leistung? Verfügbare Strommenge oder Ladezustand in % (SoC)?

Und dann zum Handling: ich tendiere dazu, die Steuerung nicht in die Konfig zu nehmen, sondern über state im channel "automatic" zu regeln. Dann kannst Du entweder einmalig Werte hinterlegen oder selbst per Script steuern, welchen Beitrag der Speicher beim Laden leisten soll.

Wenn es die o.g. WErte gibt, könnte man eine max. Leistung einstellen, die aus der Batterie entnommen werden darf und eine Untergrenze, die der Ladezustand Speicher nicht unterschreiten darf.

Diese Werte könntest Du dann z.B. in einem Skript je nach erwarteter Sonneneinstrahlung tagsüber auf 0 W begrenzen oder nur im Winter aktivieren, wenn sonst gar kein (Überschuiss-)Laden möglich wäre, weil die Sonne nicht genug Leistung bringt...

**Comment by Sneak-L8** [comment]
> Fronius.0.powerflow.P_AkkuIst ein positiver Wert in Watt, wenn der Akku Energie abgibt und damit entladen wird und ein negativer Wert in Watt, wenn der Akku geladen wird. 

Im Adapter werdne diese Werte genau anders herum interpretiert. Da soltle ich wohl eine Erweiterung machen, dass man hier auch getrennte State für Laden und Entladen hat und die je nach Vorzeichen befüllt (wie bei regard und surplus).

Kannst du hilfsweise mal einen State erstellen, der die Werte mit geändertem Vorzeichen bereitstellt und dann diesen State im adapter hinterlegen? Ich vermute, dann sollte es mit dem Laden klappen.
Dann passe ich den Adapter an.

**Comment by Sneak-L8** [comment]
> @Sneak-L8 Das Thema EMS ist auch bei mir langsam relevant (PV, Wallbox, Wärepumpe) und ich habe ja keine Keba Wallbox, von einem allgemeinen Adapter könnte ich und sicherlich viele andere profitieren.

Das ist eine berechtigte Frage. Gibt es denn schon einen allgemeinen EMS-Adapter?
Sonst wäre die Aufteilungi n zwei Adapter auch interessant. Aber etwas Aufwand, dann einheitliche/standardisierte States zu bestimmen, die mit anderen Wallboxen zurecht kommen. Bin mir nicht sicher, ob es da so etwas gibt und ob z.B. alle über die Stromstärke gestueert werden oder manche z.b. auch über die Leistung.
Zeitlich hänge ich derzeit eh hinterher und will bei zwei weiteren Adaptern noch etwas verbessern. Aber da müsste ein Tag derzeit mehr als 24h haben ...

**Comment by matthiasisrael** [comment]
Hallo Sneak,Ich habe einen State erstellt, der alle 2 Sekunden den Wert von Fronius.0.powerflow.P_Akku investiert. Der erste Test war erfolgreich!Könntest du das Invertieren im Adapter bereit stellen, damit ich nicht den Umweg über den von mir erstellten State gehen muss? LGVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Sneak-L8 ***@***.***> Datum: 29.05.22  20:51  (GMT+01:00) An: "iobroker-community-adapters/ioBroker.kecontact" ***@***.***> Cc: matthiasisrael ***@***.***>, Author ***@***.***> Betreff: Re: [iobroker-community-adapters/ioBroker.kecontact] Einbindung eines Speichers (Issue #109) 



Fronius.0.powerflow.P_AkkuIst ein positiver Wert in Watt, wenn der Akku Energie abgibt und damit entladen wird und ein negativer Wert in Watt, wenn der Akku geladen wird.



Im Adapter werdne diese Werte genau anders herum interpretiert. Da soltle ich wohl eine Erweiterung machen, dass man hier auch getrennte State für Laden und Entladen hat und die je nach Vorzeichen befüllt (wie bei regard und surplus).

Kannst du hilfsweise mal einen State erstellen, der die Werte mit geändertem Vorzeichen bereitstellt und dann diesen State im adapter hinterlegen? Ich vermute, dann sollte es mit dem Laden klappen.

Dann passe ich den Adapter an.

**Comment by Sneak-L8** [comment]
Bin ich  dran, geht aber noch etwas

**Comment by Sneak-L8** [comment]
So, neue Version steht mal bei git. Probier es mal aus bitte.

**Comment by matthiasisrael** [comment]
Hallo Sneak,

ich kann die gitversion im iobroker zwar auswählen, dann wird aber 
anschließend nichts installiert.
Kannst du mir bitte sagen, was ich falsch mache oder mir den Link 
schicken?

Gruß
Matthias


Am 2022-06-18 16:44, schrieb Sneak-L8:

**Comment by Sneak-L8** [comment]
Da bin ich überfragt. Wenn Du mit dem Katzenymbol im Reiter git kecontact aus der Dropdown-Box auswählst und dann installieren drückst, dann sollte sie auch installieren. Sollte zumindest kein spezifische Problem des Aapdaters sein. Hast Du schon im ioBroker-Forum nach einer Lösung geschaut?
Kann grad selbst nicht testen, nach OS-Update läuft mein RaspPi nicht mehr ...

**Comment by matthiasisrael** [comment]
Hallo Sneak, Nach einem Reboot meines Raspis hat es nun funktioniert. Das Auto ist gerade vollständig geladen, ich werde dir im laufe der Woche eine Rückmeldung geben...Danke!!GrußMatthiasVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Sneak-L8 ***@***.***> Datum: 25.06.22  11:32  (GMT+01:00) An: "iobroker-community-adapters/ioBroker.kecontact" ***@***.***> Cc: matthiasisrael ***@***.***>, Author ***@***.***> Betreff: Re: [iobroker-community-adapters/ioBroker.kecontact] Einbindung eines Speichers (Issue #109) 

Da bin ich überfragt. Wenn Du mit dem Katzenymbol im Reiter git kecontact aus der Dropdown-Box auswählst und dann installieren drückst, dann sollte sie auch installieren. Sollte zumindest kein spezifische Problem des Aapdaters sein. Hast Du schon im ioBroker-Forum nach einer Lösung geschaut?

Kann grad selbst nicht testen, nach OS-Update läuft mein RaspPi nicht mehr ...

**Comment by matthiasisrael** [comment]
Hallo Sneak, nach anfänglichen Schwierigkeiten funktioniert die github Version nun.Die Schwierigkeiten gab es aufgrund falscher Einstellungen meinerseits. GrußMatthiasVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Sneak-L8 ***@***.***> Datum: 25.06.22  11:32  (GMT+01:00) An: "iobroker-community-adapters/ioBroker.kecontact" ***@***.***> Cc: matthiasisrael ***@***.***>, Author ***@***.***> Betreff: Re: [iobroker-community-adapters/ioBroker.kecontact] Einbindung eines Speichers (Issue #109) 

Da bin ich überfragt. Wenn Du mit dem Katzenymbol im Reiter git kecontact aus der Dropdown-Box auswählst und dann installieren drückst, dann sollte sie auch installieren. Sollte zumindest kein spezifische Problem des Aapdaters sein. Hast Du schon im ioBroker-Forum nach einer Lösung geschaut?

Kann grad selbst nicht testen, nach OS-Update läuft mein RaspPi nicht mehr ...
