### ISSUE TITLE
Zählerstand abfragen

### ISSUE THREAD

**Issue by samoht0403** [iobroker-community-adapters/ioBroker.kecontact#110]
Hi zusammen,

toller Adapter erstmal vorweg.

Ich scheitere gerade an Folgendem: ich suche den Zählerstand, sodass ich in einem blockly-Skript für einen bestimmten Zeitraum ausrechnen kann, wie viel Energie ich getankt habe.

eTotal steht bei mir auf (null)Wh, da hätte ich es erwartet.

Falscher Datenpunkt oder was mache ich falsch?

Besten Dank,
Thomas

**Comment by Sneak-L8** [comment]
Um welche Wallbox handelt es sich genau? Eine Dautschland-Edition. Dann ist die Antwort einfach, aber zugleich ernüchternd. Sie hat keinen Energiezählen und kann die Daten daher nicht bereitstellen. eTotal ist aber der richtige State.

**Comment by samoht0403** [comment]
Danke Sneak-L8. Es ist die keba p30 und gebranded mit SolarEdge. Wenn das so ist, dass es nicht geht, muss ich wohl einen Workaround anstrengen und mir was basteln mit letzter Ladung + Basiswert = neuer Wert. Hast Du das zufällig so gemacht? Danke Dir

**Comment by Sneak-L8** [comment]
Wenn ich Googgle verstärkt sich meine Vermutung, dass die SolarEdge eine DE-Edition ist. Schau mal bitte in den State "product" endet die Kolonne mit "-DE"? Dann ist es die Deutschland-Edition.
Deine Beispielrechnung kann ich nicht ganz nachvollziehen, wie Du da was berechnen willst. Ich meine, die DE kann auch keine Ladeleistung anzeigen, also müsstest Du anhand eingestellter Stromstärke vermuten, dass mit dieser auch geladen wird und das hinreichend oft prüfen und mit dem Zeitintervall der Prüfung multiplizieren. So bekommst Du eine geschätzte Lademenge.
Dürfte aber keinesfalls genügen, um damit irgendwelche Abrechnungen oder Umlageschlüssel zu ermitteln. Dafür hast du dann leider einfach eine Nummer zu klein gekauft.
Für Dich für dne Hausgebrauch ("was hab ich grob geladen") könnte es reichen.

**Comment by samoht0403** [comment]
Cool, dass Du sogar googelst. In product steht: "KC-P30-EC2404B2-M0R-SL". Meine Beispielrechnung war wie folgt gedacht: Ich kenne den aktuellen Zählerstand der Keba indem ich über die Weboberfläche der Wallbox reingehe. Diesen würd eich als Offset nehmen und dann immer lastChargeAmount hinzuaddieren, wenn der Wert aktualisiert wurde.

Also im Grunde: Zählerstand neu = Zählerstand alt + lastChargeAmount

Das war die Idee dahinter. Klappt natürlich nur, wenn lastChargeAmount erst geändert wird, wenn das Laden beendet wurde und nicht nur unterbrochen.

**Comment by Sneak-L8** [comment]
Oh, wenn ich es richtig interpretiere, dass ist das ene x-Series mit WLAN? Da sollte durch totel auf jeden Fall gefüllt sein. Kannst du mir mal einen Screenshot vom WebFrontend und den State in ioBroker als PN schicken?

**Comment by samoht0403** [comment]
gerne. Ich sehe aber gerade nicht, wie ich in gitHub eine PN schicken (auch nicht hiermit https://github.community/t/how-to-sned-a-private-message-to-another-git/2536). Wenn Du mir sagst wie oder wohin, sehr sehr gerne.

**Comment by Sneak-L8** [comment]
ach stimmt, Adresse ist nicht public: mail an git@sengler.de. Danach lösche ich diesen Post wieder.

**Comment by Sneak-L8** [comment]
danke für Dein private Mail. Das Bild war relativ klein, aber es sieht so aus, als wären ja fast gar keine Daten da.

Könnte es sein, dass der DIP-Schalter in der für die UDP-Kommunikation nicht aktiv ist? Das hatte gerade noch ein User. Die Box ist auch „ausgeschaltet“ mit dem Netz verbunden und Sendet zumindest Ihre Kennung und Serien-Nr., vermutlich damit man auch so Updates einspielen kann.
Schau mal ins Installationshandbuch, da sollte beschrieben sein, welcher DIP-Switch es genau ist.

**Comment by samoht0403** [comment]
Tiptop, das war es. Danke Dir!
