### ISSUE TITLE
Cannot load jsonConfig of kecontact: Not exists Edit config

### ISSUE THREAD

**Issue by solo17er** [iobroker-community-adapters/ioBroker.kecontact#117]
Hello, after a ioBroker Update no MQTT Data can be sent anymore. This concerns all modules.

"Cannot load jsonConfig of kecontact: Not exists Edit config"

![2022-06-26 13_03_57-objects - iobroker](https://user-images.githubusercontent.com/73843599/175811157-2abb3162-49a9-47df-b6df-9a5ae656fbe5.png)

I need to uninstall the adapter to get the rest of my instances working again.

**Comment by Sneak-L8** [comment]
And was is the issue for the kecontact adapter? Please post your problem where appropriate.

**Comment by solo17er** [comment]
> And was is the issue for the kecontact adapter? Please post your problem where appropriate.

Sorry I thought this was caused by kecontact, maybe I am wrong. 
When i install the 1.4.0 kecontact Adapter all instances of all installed adapters telling me "Cannot load jsonConfig of kecontact: Not exists" and no one will not work via MQTT afterwards. I don't even have to create a kecontact instance. If I uninstall keconnect everything is as it should be. I therefore think that there is a problem with kecontact. I leave it uninstalled for the time being. The two wallboxes I can also monitor otherwise, apparently no one but me has the problem? All ioBroker packages are up to date and nothing unusual is noticeable in the log.

**Comment by Sneak-L8** [comment]
Did you try to install another (new) adapter? Perhaps there's the same problem. I have no idea where this error should come from.
Do you use compact mode?

**Comment by solo17er** [comment]
I have installed "Philips Hue Bridge" as a test, here the problem does not appear. The error occurred on 20.06.2022 the first time, from here I received no more MQTT messages. If no one else has the problem, it will somehow be due to my system. You can search if someone should report again.

**Comment by Sneak-L8** [comment]
Very strange. Since I have no idea where to start investigation, perhaps you can post your issue in forum.iobroker.net.
