### ISSUE TITLE
P30x keinen Kontakt mehr zu IOBroker

### ISSUE THREAD

**Issue by BeVirtualized** [iobroker-community-adapters/ioBroker.kecontact#138]
Hi, hoffe, dass mir auf diesem Wege jemand helfen kann. Nutze IOBroker mit der P30x seit über einem Jahr völlig ohne Probleme. 

Vor ein paar Wochen meldet die Instanz "Verbunden mit Host und Lebenszeichen grün" aber "Verbunden mit Gerät oder Dienst rot". Es laufen somit keine Daten mehr in den Adapter. 

Ich hab natürlich - soweit ich weiß - nichts verändert, außer dass ich irgendwann auf 1.14.0 bei der Keba gewechselt bin, aber das steht nicht im direkten Zusammenhang. Restarts der Keba, Nutzung eines anderen Ports auf dem Switch, Umstellung auf WLAN, Reinstallation des Adapters in IOBroker - alles hilft nichts. Das Webinterface der Keba kann ich problemlos erreichen, grundsätzliche Connectivität ist also da.

An den DIP Switches wurde auch nichts verändert, 1.3 steht wie seit über einem Jahr auf der richtigen Position.

Bin dankbar über jeden Tip.

VG
Thomas

**Comment by Sneak-L8** [comment]
Hm, also sobald der Adapter Daten von der Wallbox empfängt (egal ob Broadcast oder Antwort auf ein Kommando), wird info.connection auf true gesetzt. Sprich: es komme nwohl keine Daten an.
Läuft evtl. eine 2. Instanz? Oder läuft etwas anderes, das mit der Wallbox spricht (externe Anbindung, anderes Tool auf anderem Rechner, ...). Denn die Wallbox sendet immer zu dem, der zuletzt mit ihr gesprochen hat.
Alternativ mal den Adapter ausschalten und mit einem UDP-Tool Daten dirket an die Keba senden und auf dem Port lauschen. Funktioniert das?
Falls nein, stört etwas im Netz oder die Keba sendet einfach nichts mehr (Defekt?).
Kannst Du irgendwie den Netzwerkverkehr prüfen, der von der Wallbox kommt oder zur Wallbox geht?

**Comment by Sneak-L8** [comment]
Das ist komisch. Kannst Du mit der Keba maltestweise per JavaScript sprechen? Funktioniert es da?
Sendende IP-adresse und empfangende sind dieselben, oder?
Wenn beide dich nicht weiterbringt, dann bitte mal die Einstellungen posten.

**Comment by BeVirtualized** [comment]
Da ich überhaupt nicht mehr weitergekommen bin, habe ich mal Testweise auf einer anderen VM den IOBroker mit dem Keba Adapter installiert. Dort funktionierte der Zugriff. Ich nehme also an, das im Zusammenspiel von Adapter, IOBroker und Netzwerkstack irgendwas "kaputt" war. Bin jetzt auf eine Vanilla Installation umgezogen und es funktioniert wieder.

Danke Dir trotzdem für Deine Hilfe!

**Comment by Sneak-L8** [comment]
Gerne. Seltsam, aber immerhin konntest Du das Problem lösen.
