### ISSUE TITLE
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.kecontact#158]
Please consider fixing the security issue reported by dependabot:

https://github.com/iobroker-community-adapters/ioBroker.kecontact/security/dependabot/4

**Comment by Sneak-L8** [comment]
@mcm1957 Sorry, link is a dead link, no vulnerables are shown.

**Comment by mcm1957** [comment]
a little bit confusing:

I see the page shown in attachment.

![image](https://user-images.githubusercontent.com/28575778/209377137-5c462aa7-658d-4d35-a055-5350f6ea0304.png)

**Comment by mcm1957** [comment]
Are you a member of iobroker-communities?
The Message is normally visible via 

Menue SECURITY -> View dependabot alerts.

**Comment by mcm1957** [comment]
I'll attach the message as plain text too:

```
Dependabot cannot update glob-parent to a non-vulnerable version
The latest possible version that can be installed is 3.1.0 because of the following conflicting dependencies:

eslint@8.26.0 requires glob-parent@^6.0.2
gulp@4.0.2 requires glob-parent@^3.1.0 via a transitive dependency on glob-stream@6.1.0
gulp@4.0.2 requires glob-parent@^3.1.0 via a transitive dependency on chokidar@2.1.8
No patched version available for glob-parent
The earliest fixed version is 5.1.2.
```

**Comment by mcm1957** [comment]
@Sneak-L8 
One additional question to you:
According to Revision History you are working on this adapter. Would it be ok for you to add you as primary maintainer for this adapter at this (https://github.com/iobroker-community-adapters/info#maintainers) list? That's only to signal whom to contact in case of priority questions. It's no obligation but it would be fine if you give some feedback if you are no longer interested or you cannot maintain the adapetr for any reason.
Thanks for your answer.
Martin (mcm1957)

**Comment by Sneak-L8** [comment]
Hi Martin, yes that's ok, absolutely.

**Comment by Sneak-L8** [comment]
I still don't see any issues:
![grafik](https://user-images.githubusercontent.com/34042079/209522832-b7cafa7e-05a9-48e8-8d2e-fd5fb3e37346.png)
And to be honest, I'm not that familiar with the dependencies to see what version I should go to. I just use the dependencies provided ...

**Comment by Apollon77** [comment]
Ignore .... It is only a topic in the dev-dependencies because glob-parent seems to be used by gulp and as long as gulp do not update the dep there is no chance for us to do anything here
