### ISSUE TITLE
Wallbox in active mode discharges PV battery

### ISSUE THREAD

**Issue by Exc3pt10n** [iobroker-community-adapters/ioBroker.kecontact#178]
The wallbox discharges the PV battery, if PV-Power lowers and the grid power doesn't  go up.

![Screenshot 2023-03-18 164346](https://user-images.githubusercontent.com/12965727/226115919-0b8dcaa5-94ae-4046-9451-ac693ce53e4f.png)

You can see on the screenshot, that grid power (Bezug) is 0 and the PV battery is discharging with 1,6 kW. I would expect, that the Charging Power (Überschuss PV = Surplus State of adapter) goes down so the PV battery wouldn't be discharged.

Configuration:

![Screenshot 2023-03-18 164653](https://user-images.githubusercontent.com/12965727/226116075-8aaf5f6a-3db4-493c-a4b1-e751edc88b51.png)

**Comment by Sneak-L8** [comment]
As you can see in tooltip of first option for battery that negative values mean discharging of battery and the will be used for charging the vehicle.
Same for second config.
So, (I don't have a battery yet) I'd advice you to clear 2nd option. So, if you don't specifiy discharging amout, battery should not be used for charging your vehicle.
If not, please try latest version on github if this would solve your problem.

**Comment by Exc3pt10n** [comment]
Okay, thank you. I will try this and give you feedback.

**Comment by Exc3pt10n** [comment]
Hallo Sneak-L8, ich hoffe auf Deutsch ist auch okay?
Ich habe heute das Ladeverhalten beobachtet und folgendes festgestellt:
Ausgangssituation war, dass die PV-Anlage noch Strom lieferte, jedoch der PV-Speicher nicht mehr geladen wurde. Ich habe dann das Auto eingesteckt und erwartungsgemäß hat die Wallbox mit der dauerhaft zulässigen Ladeleistung geladen. Als jedoch ein weiterer Verbraucher dazu kam (Backofen) und anschließend wieder ausgeschaltet wurde ist die Ladeleistung angestiegen, wobei ich erwartet hätte, dass die Ladeleistung wieder auf die dauerhaft zulässige Ladeleistung zurückgeht. ISt das so gewollt? Ich werde aus der Doku nicht so ganz schlau was das angeht.

**Comment by Sneak-L8** [comment]
Klar, Deutsch ist völlig in Ordnung :-)
Hm, also die Ladeleistung sollte durch den Backofen fallen und nachdem ausschalten wieder ansteigen.
Kannst Du Deine Beschreibung um ein paar Zahlen ergänzen? Also was zeigte das EnergyMeter an als Du den Backofen angremacht hast und was, als er wieder aus war etc.
Wie ich sehe, hast Du auch "nur" die Deutschland-Edition. Diese hat keinen Energiezähler und so schätze ich den Strombezug, indem ich immer annehme, dass das Auto mit der angebotetenen Leistung auch wirklich lädt.

Am besten wiederholst Du den o.g. Vorgang und postet mal das Log, nachdem der Adapter auf Debug gestellt wurde. Dann stehen im Log die Grundlagen der Berechnung des Adapters.

**Comment by Exc3pt10n** [comment]
Hallo Sneak-L8,
ich habe heute, an einem wechselhaften Tag, das Ladeverhalten beobachtet.
Es ist so, dass die Vermeidung von Bezug aus dem Stromnetz sehr gut funktioniert - hier gibt es nichts zu meckern. Sehr gute Arbeit.
Was mir jedoch aufgefallen ist, ist das die maximale Ladeleistung der Wallbox nur dann heruntergeregelt wird, wenn Bezug aus dem Stromnetz stattfindet. Hier mal als Beispiel ein Screenshot, wo man sieht, dass die maximale Ladeleistung hochgehalten wird, da es keinen Bezug aus dem Stromnetz gibt:

![Screenshot 2023-03-25 162932](https://user-images.githubusercontent.com/12965727/227727142-3d6dfafa-3a14-4f67-8eb1-a4a883e0ca7d.png)

Könntest du evtl. darüber nachdenken einen weiteren State hinzuzufügen, wo man durch einen True oder False Wert steuern kann, ob die Ladeleistung auch bei Entladung aus dem Stromspeicher auf den minimal eingestellten Wert herabgesenkt wird? Quasi eine Priorisierung zwischen Auto laden und PV-Speicher minimal entladen.

Ich hoffe, das war einigermaßen verständlich, sonst gerne nachfragen.

Vielen Dank im Voraus!

**Comment by Sneak-L8** [comment]
Klingt nach einem guten Gedanken. Ich habe die Option mal eingebaut. Bitte Version von github installieren und testen.

**Comment by Sneak-L8** [comment]
So, ich habe es gerade nochmal überarbeitet.
Ich habe noch einen 3. State eingeführt, den es hoffentlich gibt, nämlich einen Wert, was der Batteriespeicher aktuell an Leistung abgeben könnte. 

Denn bisher habe ich das Entladen des Speichers nicht korrekt berücksichtigt. Die bisherigen beiden States sind nun wie bei Überschuss und Netzbezug einfach zu subtrahieren. Hab ich Laden und Entladen in einem State, dann fülle ich auch nur einen der beiden. Gebe ich nur diese beidne an, dann wird für das Laden des Autos nur die Leistung mit der der Batteriespeicher gerade geladen wird mit einberechnet, aber nie Strom aus der Batterie entnommen.
Gebe ich den 3. State an,der mir sagt, wieviel ich maximal an Leistung aus der Speicher entnehmen kann, dann wird diese auch zum Laden des Fahrzeugs genutzt.
Wenn ich nun die Option "Leistung des Batteriespeichers begrenzen" angebe. dann wird die verfügbare Leistung des Speichers dazu genutzt, das Fahrzeug mit minimaler Leistung weiter zu laden. wenn der Überschuss sonst nicht ausreichen würde.
Der Speicher wird also nur angezapft, wenn das Auto schon lädt und sonst mangels Überschuss nicht weiterladen würde.
Passt das so?

**Comment by Exc3pt10n** [comment]
Hallo Sneak-L8,
vielen Dank für die schnelle Implementierung.
Ich habe die aktuelle Version von GitHub installiert und folgende Konfiguration vorgenommen:

![Screenshot 2023-04-03 084634](https://user-images.githubusercontent.com/12965727/229432294-5bbfc270-3874-4d9e-9cae-766059f29428.png)

![Screenshot 2023-04-03 084736](https://user-images.githubusercontent.com/12965727/229432305-9181fe34-0240-44d1-ad05-5b120b8a85e4.png)

Ich denke der Parameter für die maximale Leistungsabgabe des PV-Speichers kann in die Adapterkonfiguration, da sich dieser nicht ändert.

Bisher läuft es so sehr gut, ich beobachte es mal weiter.

**Comment by Sneak-L8** [comment]
Danke für Deine Rückmeldung. Ich hatte gehofft, es gbt einen variablen Wert für die max. Leistungsabgabe. Die müsste ja sinken, wenn der Batteriespeicher langsam leer läuft. Ist er leer, müsste der Wert null sein. Gibt es sowas nicht?

**Comment by Exc3pt10n** [comment]
Zumindest bei meinem QCells Hybrid-Wechselrichter gibt es keinen Wert, der das angibt. Im Prinzip ist es so, dass mein PV-Speicher 3 kW entladen kann und 2 kW laden. Das hält er auch bis zu einem SoC von 10% durch. Ich möchte den PV Speicher für das E-Auto normalerweise nur als Puffer verwenden, wenn es Wechselhaft ist und ich PV-Optimiert lade. Wenn ich weiß, dass ich in 3 Stunden weg muss, dann stelle ich sowieso auf volle Ladeleistung.

**Comment by Sneak-L8** [comment]
Ok, wenn ich sehe, dass die aktuelle Lade-/Entladeleistung auch von einem eigenen State von Dir kommen, dann könntest Du einen weiteren anlegen, der bei einem SoC > 10% 3 kW angibt und darunter 0 kW. So könnte man mal ins Rennen gehen.

**Comment by Exc3pt10n** [comment]
Hallo Sneak-L8,
ich habe wie besprochen die Anpassungen an der Konfiguration vorgenommen und stelle auch einen Wert für die maximale Entladeleistung des PV-Speichers in Abhängigkeit vom SoC bereit.

![Screenshot 2023-04-05 133531](https://user-images.githubusercontent.com/12965727/230069145-704cf1f9-a538-4925-bb96-3e90223bd542.png)

Jetzt ist es jedoch so, dass er aktuell bei mir lediglich mit dem minimalen Ladestrom das Auto lädt, obwohl ausreichend PV-Überschuss vorhanden ist:

![Screenshot 2023-04-05 133442](https://user-images.githubusercontent.com/12965727/230069303-4b826968-f552-4355-840a-81068158635a.png)

Dabei gilt:
PV-Überschuss = Surplus aus Adapter Datenpunkten
Max. Entladung Speicher = Neuer Wert für die Entladeleistung des Speichers
Max. Ladeleistung = currentUser * 0,23

Protokoll ist anbei. Könntest du Dir das mal ansehen?

Vielen Dank im Voraus

 
[ioBroker.kecontact.pdf](https://github.com/iobroker-community-adapters/ioBroker.kecontact/files/11158298/ioBroker.kecontact.pdf)

**Comment by Sneak-L8** [comment]
Ok, die Berecnung hab ich verstanden, aber für was hat sie mit dem KeContact-Adapter zu tun? Oder ist das nur die Erklärung für Deine Visualisierung?
Ich hatte übrigen noch einen Fehler beim "Ladeleistung limitieren", daher wurde immer mit 6A gelasen. Jetzt sollte mit der Option nur die Leistung der Batterie entnommen werden, die zum Aufrechterhalten der Ladesitzung nötig ist.
Version steht jetzt auf github bereit zum Testen :-)

**Comment by Exc3pt10n** [comment]
In erster Linie war es eine Erklärung für die Vis, da dort eine Leistung steht und nicht wie vom Adapter gesetzt eine Stromstärke. Ich denke der Adapter hat aufgrund des hohen PV-Überschuss auf 3 phasiges Laden umgestellt und somit je Phase mit 6A geladen. Kann ich irgendwo einstellen, dass er nur mit einer Phase laden soll? Mehr kann der Onboard Charger von meinem Hybrid nicht. 

Das Update schaue ich mir Morgen mit dem nächsten Ladevorgang einmal genauer an :)

**Comment by Sneak-L8** [comment]
Du musst wegen der Phasenn ichts einstellen. Sofern Du keinen Installationsschütz oder den S10 von Keba isntallierst hast, werden dem Fahrzeug immer 3 Phasen angeboten. Der Adapter merkt dann je Phase, ob Strom fließt und erkennt die geladenen Phasen selbst.
Ach Moment, Du hast die Deutschland-Edition gell? Da gibt es keine Leistungsmessung und ich kann nur raten. Da musst Du unter kecontact.0.automatic.calcPhases die Anzahl Phasen einstellen, da sie nirgend berechenbar sind. Einfach unter "Objects" den Wert hinterlegen. Dann stimmt auch die Berechnugn mit Überschuss etc.

**Comment by Exc3pt10n** [comment]
Vielen Dank für das Feedback, teste ich direkt mal. Muss ich den Wert einmalig setzen oder immer wieder, da der Adapter den Wert evtl. anpasst?

**Comment by Sneak-L8** [comment]
Einmal sollte reichen
