### ISSUE TITLE
Include a heat pump into the logic

### ISSUE THREAD

**Issue by Martin1085** [iobroker-community-adapters/ioBroker.kecontact#209]
Hi,

i have a additional idea to include into this awesome tool.
In my home i have a heat pump for heating the house or making warm water.
If i have PV Surplus, i start to warm the water to a normal temp eg. 50°C if not i just have 45°C. I start to load my car only if the Water is on nomal state. If the car is full and i still have surplus, I heat the Water to 58°C (maximum for my heatpump).
With this logic i can survive a day with no sun without heating the water with buyed energy.

**Comment by mcm1957** [comment]
Managing PV surplus is outside of the goals of this adapter.

You cann implement this behaviour using javascript or blockly.
Maybe a look at https://github.com/ioBroker/AdapterRequests/issues/843 and https://github.com/Newan/ioBroker.pv-power-control could help too. Eventually a issue at the referenced adapter would by useful.
