### ISSUE TITLE
Estimate Power for KEBA KeContact P30 DE440 

### ISSUE THREAD

**Issue by christi-ko** [iobroker-community-adapters/ioBroker.kecontact#217]
**Describe the bug**  
The Keba DE440 is not including a power meter. I assume therefore no power is available to the adapter, therefore some informations are not available but could be assumed

**To Reproduce**  
Start a loading session with the KEBA DE440.
All variables with power, current and voltage stay at zero, eg (eStart, ePres, eTotal, p)

**Expected behavior**  
I would propose to calculate / estimate the power or variables  with the the commanded or default one and current amount of used phases. Therefore the whole functionality of the adapter would be useable even without power meter.

I would like to be able to use the setenery to define the power to be charged.

**Screenshots & Logfiles**  
not requried.

**Versions:**  
I use the latest version of the adapter 2.0.1

Thank you for the great adapter. I am already very happy with it and i just started to create a workaround. But having this in the adapter would make life a bit easier.

**Comment by Sneak-L8** [comment]
Are you able to provide product ID of DE440?
Adapter already supports "Keba Deutschland Edition" that also lacks of power meter. Therefore there's a state "calcPhases" to provide nmber of phases vehicle would charge with. For that edition power consumption is asumed to be always full power by 230V * calcPhases * current amperage.
If DE440 behaves like a "Deutschlang Edition" I just have to add the product ID of that charging station.

**Comment by christi-ko** [comment]
Hallo Sneak,
Also ich dachte ich hätte eine Deutschland Edition. Aber wer weiß:
Meine ID laut Adapter: KC-P30-EC220432-000-DE

**Comment by Sneak-L8** [comment]
Ja, das ist eine Deutschland-Edition. Das wird ja auch im Log ausgewiesen. Die Berechnugn erfolgt wie oben beschrieben mit den kalkulierten Werten. ePres, P, etc. sind aber Werte die 1 zu 1 aus der Wallbox in die States eingetragen werden. Dort steht daher null, auch wenn intern mit den passenden Werten gerechnet wird.

**Comment by christi-ko** [comment]
Alles klar, habe ich mir gedacht. Der Gedanke war ob man die genannten internen States direkt im Adapter für die Deutschland Edition rechnet soweit möglich, da ja intern in der Keba nichts gemacht wird. Aber ist eher ein zweitrangiges Thema.  Wenn so nicht sinnvoll kann man das auch ablehnen und wir schließen die Issue

**Comment by Sneak-L8** [comment]
Ich würde jetzt nicht unbedingt Werte, die ja von der Keba (mit 0) geliefert werden, überschreiben. Daher wäre ich dafür, den Issue zu schließen.

**Comment by christi-ko** [comment]
Alles klar, das hätte ich auch so verstanden. Ich schließe die Issue
