### ISSUE TITLE
Strange Surplus value

### ISSUE THREAD

**Issue by Ytnom2404** [iobroker-community-adapters/ioBroker.kecontact#249]
Hello,

I am on Iobroker adapter version 2.0.1.
I noticed that my PV automatics does not start stop correctly. When i now removed all entries for surplus, battery etc it still shows surplus to be 13ßßkw..Where does this value come from if no datasource was provided`?
Could you please explain the calculation for surplus, regard state and battery charge and dischare with the surplus calculation.

Thank you

With kind Regards
Michael

**Comment by Ytnom2404** [comment]
Can be closed…. Was my mistake… it works now

**Comment by mcm1957** [comment]
Thanks fro info
