### ISSUE TITLE
Zustand zum Schalten von 1 Phase auf 3 Phasen

### ISSUE THREAD

**Issue by Eulili** [iobroker-community-adapters/ioBroker.kecontact#263]
Der Zustand der Phasenumschaltung wird anscheinend auch ausgeführt, wenn die Wallbox auf "Dauerbetrieb" (also ohne Überschussladung)  oder auf "AUS" (keine Ladung) eingestellt wird. Ist das nur bei mir so?

Vielen Dank für die Mühe bei dem genialen Adapter

**Comment by Sneak-L8** [comment]
Ich bräuchte ein paar Infos mehr. 
* Was meinst Du mit Zustand Phasenumschaltung? Die Umschaltung ist ein Vorgang. Welcher status ist gemeint?
* Wann konkret wird die Phase (und von 1 auf 3 oder 3 auf 1) umgeschaltet?
* Was meinst Du mit Dauerbetrieb? "passive Modus" oder "automatics = false"?
* Was für ein Schütz wird verwendet?
* Öffner oder Schließer?
* Über X2-Ausgang oder "Eigeninstallation"?

Gedacht ist es so, dass der Schütz (egal ob Öffner oder Schließer) ohne angeschlossenes Auto immer aus ist.
Ist ein Auto angeschlossen, kommt es auf den Typ des Installationsschützes an. Wenn die Automatik aus ist, dann ist der Schließer dauerhaft an. Denn die Box weiß ja nicht, wann das Auto anfängt zu laden. Und wenn die Box im Status signalisiert, dass sie lädt, ist es zu spät, um die Phase umzuschalten.

**Comment by Eulili** [comment]
> Gedacht ist es so...

Jetzt habe ich es auch verstanden ;-) DANKE! Muss ich mein System halt umbauen, da ich mit einem Schütz zwei getrennt geregelte Wallboxen schalte (sind gegeneinander verriegelt).
