### ISSUE TITLE
Batteriespeicher priorisiert behandeln

### ISSUE THREAD

**Issue by matthiasisrael** [iobroker-community-adapters/ioBroker.kecontact#276]
Hallo zusammen,

zunächst vielen Dank für den tollen Adapter! Hat im Sommer wirklich super funktioniert 😀

Im Herbst habe ich nun folgende Situation:
Unser 14kWh - Batteriespeicher ist morgens häufig leer oder annähernd leer und wird dann bei dem derzeit bewölkten Wetter nur langsam geladen.
Klart es dann für einen Moment auf kann unsere Batterie scheinbar nicht den gesamten PV-Überschuss aufnehmen und speist diesen dann ein. Häufig wird hierbei kurzzeitig die Grenze für das PV-Überschussladen erreicht, sodass dann der Ladevorgang startet (obwohl der Batteriespeicher noch nicht die in den Adaptereinstellungen hinterlegten Mindest-SOC erreicht hat).
Schiebt sich nun wieder eine Wolke vor die Sonne bricht der PV-Überschuss schlagartig ein und das Laden wird für die Mindestdauer fortgesetzt (genau wie im Adapter eingestellt). Dabei wird jedoch der Batteriespeicher entladen.
Auf diese Weise fließt häufig Energie ins E-Auto, die ich dort nicht zwingend bräuchte und in der Nacht ist dann leider der Batteriespeicher leer.

Daher meine Fragen: 
1. Ist es möglich, vor Beginn des Ladevorgangs zu überprüfen, ob der Mindest-SOC aus den Adaptereinstellungen erreicht ist und nur dann den Ladevorgang zu starten?
2. Die Ladeleistung um x Watt zu reduzieren, um diese x Watt zum Laden der Batterie zu verwenden bis der Mindest-SOC aus den Adaptereinstellungen erreicht ist?

Gruß
Matthias

**Comment by geigl** [comment]
Hallo, hast du bereits die neueste Version von Github in Verwndung? Bei dieser kann man die Priorisierung auswählen.

**Comment by mcm1957** [comment]
VON DIrekteN Installationen von Github WIRD DRINGEND abgeraten ausser der Entwickler empfiehlt diese explizut zur Fehleranalyse od als Hotfix.

Der Stand auf Github kann sich jederezeit ändern und auch komplett fehlerhaft sein.

Im Normalfall aollte nur von LATRST oder STABLE  repository installuert werden. Ggf bitte den Maintainer ersuchen eibe neue Release zu erstellen sollte das nal vergessen wurden sein.

**Comment by geigl** [comment]
Den Hinweis auf die neueste Version auf Github hat der Entwickler im iobroker-Forum gegeben.

**Comment by mcm1957** [comment]
> Den Hinweis auf die neueste Version auf Github hat der Entwickler im iobroker-Forum gegeben.

Danke für Klarstellung. Wenn es der Dev anregt / empfiehlt ist es i.O. Er wird ja - zumindest wenn es keine Probleme gibt - zeitnahe eine Release erstellen.

Es sollte nur vermieden werden User die nicht als Tester fungieren auf Github zu lenken da dies allenfalls den Support erschwert. (Versionen auf Github sind nicht trivial nachvollziehen. Versionen werden werden im allgemeinen erst beim Release angepasst / erhöht).

**Comment by matthiasisrael** [comment]
Vielen Dank für den Tipp.
Nein ich habe Version 2.0.2 installiert.
Kannst du mir sagen, welche url ich nutzen muss?

**Comment by matthiasisrael** [comment]
Vielen Dank für den Tipp!

Habe Version 2.0.2 von GitHub installiert und nun sind die von dir beschriebenen Einstellmöglichkeiten verfügbar.
Ich versuche es in meinem Fall mit Zeile 2 (Verwenden Sie keinen Batteriespeicher zum Laden des Fahrzeugs, sondern geben Sie dem Batteriespeicher Vorrang)

**Comment by geigl** [comment]
Dies sollte die korrekte Einstellung sein.

Die Diskussion und Fragen zum Adapter werden hier geführt:
https://forum.iobroker.net/topic/6343/frage-realisierung-adapter-udp-keba-wallbox/860?_=1698518343308

Sneak-L8 ist für gestellte Fragen immer zugänglich. Von ihm bekommst du die richtigen Antworten sollte etwas nicht wie gewünscht funktionieren.

**Comment by matthiasisrael** [comment]
@geigl Vielen Dank für den tollen Support!

**Comment by Sneak-L8** [comment]
Ja, bitte mal von github testen. Der Umstand, dass die Batterie geladen werden soll, solange der minSoC nicht ergreift wird, gibt es noch nicht. Aber der Vorrang der Batterie sollte ja bewirken, dass ein Laden dieser nicht beeinträchtigt wird. Daher bitte mal so testen mit der Option 2.

**Comment by User-Roman** [comment]
Hallo an Alle,
ich habe hier einiges über dieses Keba Projekt gelesen und finde es sehr spannend.
HA habe ich erst wenig Wochen installiert und bin noch richtiger Newbee.
Zuerst hatte ich Keba per Eintrag "configuration.yaml" laufen, aber denke das hat nichts mit Deinem Projekt zu tun.
Dann habe ich es geschafft den richtigen Link aus GitHub zu finden (echte Herausforderung für einen Newbee) um es unter HACS/"Benutzerdefinierte Resposertories"  einzubinden und darüber im Anschluss herunterzuladen. Nach dem Neustart bekam ich die Meldung,  dass ich den vorher erstellten Keba Eintrag (noch von dem Erstversuch einer Keba Einbindung) in der configuration.yaml entfernen soll. Nach dem Entfernen (und Neustart) stehen die Entitäten unter "Aktuelle Entitäten" der ersten Keba Einbindung nicht mehr zu Verfügung (unavailable), aber es sind auch keine Neuen hinzugekommen. 

Habe ich etwas falsch gemacht oder muss ich noch etwas zusätzlich ausführen? 

Falls Ihr mir helfen könnt und wollt, wären detaillierte Anweisungen/Ausführungen sehr willkommen (Newbee, ich kämpfe fast noch mit jeder Anweisung die ich ausführen soll. Da sind Bilder und Videos sehr hilfreich.) Ich kann mir gut vorstellen das ich nicht der Einzige bin und sich warscheinlich viele Newbees sich über eine eigene detaillierte Anweisung/Ausführung hierzu freuen würden.

So wie ich es mir bisher zusammen reime, gibt es zwei grundsätzliche Aktionen die umzusetzen sind.
1) Per HACS etwas on HA einzubinden 
2) Die Firmware der Wallbox (P30) zu flashen
(Ich gehe davon aus, dass "Python library for controlling KEBA charging stations" sich auf das Flashen der WB Firmware bezieht.)


Gruß, Roman

PS: Falls dies hierfür die falsche Platzierung ist, bitte ich vorab um Entschuldigung.

**Comment by Sneak-L8** [comment]
Deine Abkürzung "HA" steht vermutlich für HomeAssistant. Der Adapter in diesem Repo ist aber für ioBroker. Das ist eine andere SmartHome-Plattform. Da musst Du Dich woanders hinwenden.

**Comment by User-Roman** [comment]
Ja das steht für Home Assistant.
Sorry, ich dachte es wäre für den Brocker von Home Assistant.

**Comment by User-Roman** [comment]
Habe es wieder gelöscht, um die Diskussion hier nicht unbeabsichtigt "aufzublähen".

**Comment by Sneak-L8** [comment]
Dann bitte den Ret auch löschen.

**Comment by Sneak-L8** [comment]
Ich mache hier mal zu, da es seit mehr als 2 Monaten keine weiteren Rückfragen mehr gab.

**Comment by mcm1957** [comment]
@Sneak-L8 
>Ich mache hier mal zu, da es seit mehr als 2 Monaten keine weiteren Rückfragen mehr gab.
Die letzte Version 2.0.2 ist von 10. Oktober.
Das Issue ist vom 27.Oktober. Am 28.10. wurde empfohlen von Github zu testen.

Es ist daher anzunehmen dass eine Verbesserung im Giuthub Code existiert die noch nicht eingang in eine Release gefunden hat.

**Comment by Sneak-L8** [comment]
@mcm1957  Release hab ich vorgestern erstellt. Hab Deine Nachricht gerade erst gesehen. Obwohl Du mich erwähnt hattest, bekam ich keine Benachrichtigung...
Schließe ich dann den issue sofort oder erst, wenn das Release ins stable wandert?

**Comment by mcm1957** [comment]
Sobald eine Release erstellt ist und damit auf Latest verfügbar ist kann ein Issue jedenfalls geschlossen werden.
Manche machen es schon früher, d.h. beim commit zu. Find ich weniger toll - aber man muss nicht alles in Regeln pressen.
Was ich gut finde ist wenn der dev in den issue reinschreibt ab welcher Version etwas gefixed ist. Erleichtert spätere Suche. Aber ist auch eine persönliche Ansicht :-)

Ergo zu mit dme Issue ...

**Comment by mcm1957** [comment]
fixed with 2.1.0
