### ISSUE TITLE
Statistics are not populated after a new installation

### ISSUE THREAD

**Issue by jwiesel** [iobroker-community-adapters/ioBroker.kecontact#28]
Hi,
thanks for creating this adapter! Very helpful!
After some little issues in the beginning, I got it to work (see #27 )

I've been playing around with the adapter a little bit and realized, that none of the statistics are not filled since I installed the adapter (e.g. lastChargeStart, lastChargeFinish, ...). I connected the car, charged and unplugged it in the meantime, but no update. My Wallbox has a fixed cable installed. --> the state only changes between "3" and "7".
When checking the source code I realized, that you implemented that functionality based on a regular wallbox check.
When I plug in my car into the wallbox I would expect the log-entry "vehicle plugged to wallbox" of kecontact.js line 520 would appear, but it doesn't.

Therefore I assume the calculation of "wasVehiclePlugged" in line 517 of kecontact.js has trouble with a new installation where the field never got populated.
Can you please have a look? I can provide additional infos, logs, etc. if needed.

When reading the UDP Programmers guide, I learned about a datagram, that provides the data you calculate:
https://www.keba.com/download/x/4a925c4c61/kecontactp30udp_pgen.pdf chapter: 3.2.5 on page 17 says, that the last charging sessions are available via datagram "report101" - "report130".

**Comment by jwiesel** [comment]
P.S: Regarding historic charges: I just checked the other forks and realized, and realized the history part is currently being implemented by @Jarves020.
See: https://github.com/Jarves020/ioBroker.kecontact/compare

**Comment by Jarves020** [comment]
Hi,

created Pull Request Today.

Added the Report100-130 commands as described in UDP Documentation.
Data is Stored in the Adapter under a seperate "Sessions" Object.
Session_00 contains the Data of the current running or last (if no new Session was started) Charging Session (Report100).
Session_01 to Session_30 containing the Data of the last 30 charging Sessions (Report101-130).

The only 2 Session States that are empty on my BMW Wallbox are the "RFID_tag" and "RFID_class" fields (FW 1.6.1).
Perhaps someone with a KEBA Wallbox with a newer Firmware could check if the States are populated with Values....

For Details see UDP Documentation: [https://www.keba.com/download/x/4a925c4c61/kecontactp30udp_pgen.pdf](url)

**Comment by marv2622** [comment]
Hi @Jarves020 ,

> The only 2 Session States that are empty on my BMW Wallbox are the "RFID_tag" and "RFID_class" fields (FW 1.6.1).
Perhaps someone with a KEBA Wallbox with a newer Firmware could check if the States are populated with Values....

Yes that's right, I have a Keba C and also don't get the RFID States with the newest Firemware (P30 v 3.10.27).
Could you please check why the RFID-States will not be filled?
In the Raw JSON string I get the RFID value, but not in the value "rfid_tag".

Thank you in advance for your support !
If you need some logs or something else, let me know.

**Comment by Jarves020** [comment]
HI @marv2622,

had a quick look at the problem.
The only error i have seen so far, is that the udpkey of the rfid_tag object was not matching the lettering in the Kecontact UDP Manual.
I've fixed it in my Fork of the Adapter.
[https://github.com/Jarves020/ioBroker.kecontact](url)

Can you test it?
If it works, i'll create a Pull request to the base repository.

Would also be interesting to see the content of your RAW JSON string, because my Wallbox only delivers the RFID class parameter....
But please mask your "Serial" in the JSON String before posting...

**Comment by marv2622** [comment]
Hi @Jarves020 ,

the object rifd_tag is now filled with the right value. :-)
Thank you very much!

RAW JSON looks as follows (Serial and RFID changed):
[{"ID":"100","Session ID":12,"Curr HW":16000,"E start":489909,"E pres":9719,"started[s]":1616238031,"ended[s]":1616238394,"started":"2021-03-20 11:00:31.000","ended":"2021-03-20 11:06:34.000","reason":1,"timeQ":3,"RFID tag":"0444e18a115f8000","RFID class":"00000000000000000000","Serial":"00000000","Sec":356114}]

kind regards
marv2622

**Comment by Sneak-L8** [comment]
Everything mentioned here should be fixed in the meantime.
