### ISSUE TITLE
P30 v 3.10.27 not working properly

### ISSUE THREAD

**Issue by xmace** [iobroker-community-adapters/ioBroker.kecontact#333]
current adapter version is not properly working with keba SW P30 v 3.10.27

control "pause wallbox" & "use photovoltaics" is not working

reading current states, power and so on is not working anymore.

Maybe API changed due to SW update.

Please check.
Debug with my system remotely is possible.

**Comment by Sneak-L8** [comment]
This is an old firmware. Current firmware for Keba P30 a-/b-/c-/e-Series is 3.10.51.
I doubt you updated to 3.10.27. If so, please provide more information on wallbox model, from which firmware version did you update, what means "not working" ...
Please provide debug log around the time switch the mentioned options.

**Comment by Sneak-L8** [comment]
no reply since two weeks, issue is closed
