### ISSUE TITLE
Unsupported state change: kecontact.0.automatic.batterySoCForCharging

### ISSUE THREAD

**Issue by fischmi** [iobroker-community-adapters/ioBroker.kecontact#334]
**Describe the bug**  
When i change the object kecontact.0.automatic.batterySoCForCharging i get following error:
Unsupported state change: kecontact.0.automatic.batterySoCForCharging

**To Reproduce**  
1. Set the object kecontact.0.automatic.batterySoCForCharging to 80.
2. See error in log

I think the solution is, to add the following three lines to the start-methode:
`     stateChangeListeners[adapter.namespace + "." + stateMinimumSoCOfBatteryStorage] = function (oldValue, newValue) {
        // no real action to do
    };`

**Comment by Sneak-L8** [comment]
Thanks for your hint and pull request. It was just merged.
