### ISSUE TITLE
Batteriespeicher einbinden in PV optimierte Ladung  // Integrate battery storage into PV optimized charging

### ISSUE THREAD

**Issue by tminimax** [iobroker-community-adapters/ioBroker.kecontact#338]
Hallo,
gibt es eine Möglichkeit beim Keba Adapter z.B. bei der PV optimierten Ladung nicht nur den PV-Überschlüssstrom heranzuziehen, sondern zusätzlich auch vom Batteriespeicher z.B. 2-3KW mit zu entnehmen für die Ladung des Autos? 
Wenn ja, wie stellt man das ein?

Generell komme ich mit der Batteriespeichereinbindung nicht zu recht. Wer kann da helfen? Gibt es wo ein Forum dazu?
Neu gibt es da jetzt ja 4 Speicher-Nutzungsstrategien, wann sollten die greifen? Bei PV Ladung oder bei normaler voller Ladung?

Danke

Thomas

Hello,
Is there a possibility with the Keba adapter, e.g. for PV optimized charging, not only to use the PV excess current, but also to take e.g. 2-3KW from the battery storage for charging the car?

If so, how do you set that up?

In general, I don't get along with the battery storage integration. Who can help? Is there a forum for this somewhere?
There are now 4 battery usage strategies, when should they take effect? With PV charging or with a normal charge?

Thanks

Thomas

**Comment by mcm1957** [comment]
You can ask such questions at iobroker forum. Its mire likely to get fast answers there

https://forum.iobroker.net

**Comment by Sneak-L8** [comment]
Since question is discused in forum [here](https://forum.iobroker.net/topic/6343/frage-realisierung-adapter-udp-keba-wallbox/959) issue is closed
