### ISSUE TITLE
1phase zu 3 Phasen Mindeststromstärke

### ISSUE THREAD

**Issue by 69paulus** [iobroker-community-adapters/ioBroker.kecontact#362]
Hallo, hätte eine frage,
 ich habe eine Keba p30 22 kw. und einen kia Soul Bj. 2018 der mit nur eine Phase lädt, für den Kia Soul läuft alles  prima, die  Wallbox regelt genau wie es soll, ist ja auch nur 1 Phase
Aber seit etwa 1 Woche  habe ich einen Ioniq 5 noch dazu bekommen der mit 3 Phasen lädt, und  die Wallbox regelt zwar wie immer noch bis 5000 mA dennoch zieht immer noch ca. 3287 Watt, das ist auch korrekt so.
Adapter  Konfiguration ist es tatsächlich möglich, aber die Wallbox regelt nur bis 5000mA obwohl ich auch 4000 mA eingestellt habe
 Die frage wäre ob das an dem Kekontakt Adapter liegt  oder an die Keba Wallbox ?
Was der ioniq5 angeht,  habe ich nirgends gefunden welche Mindestladestrom der ioniq 5 braucht.

wenn das nicht viel Stress bereitet, würde mich freuen über eine Antwort 
Viele Grüße Paul

**Comment by Sneak-L8** [comment]
Die Mindeststromstärke liegt eigentlich bei 6A. Man kann sie tiefer setzen und bei einigen funktionieren auch 5A. Aber man sollte beachten, dass die Verlustleistung höher (der Wirkungsgrad also niedriger und Strom verschenkt) wird.
Das ist der "Nachteil" eines Autos, das mit 3 Phasen lädt. Die Mindestleistung ist deutlich höher.
Lösen lässt sich das nur über einen Phasenumschalter (ist eher ein "Abschalter" von 2 Phasen), den es direkt von Keba gibt, man auch auch selbst bauen kann. Der Adapter kann damit umgehen und so auch bei niedrigerem Überschuss das Auto voll machen. Hab ist seit letztem Jahr und im Winter war die PV-ausbeute dadurch deutlich höher.

**Comment by 69paulus** [comment]
Hallo, danke für die schnelle Antwort, und für die Info, super Beratung, und danke auch für den Ratschlag, ich werde es mal ausprobieren.
viele Grüße Paul
