### ISSUE TITLE
Not connected to device

### ISSUE THREAD

**Issue by Martin-Stein** [iobroker-community-adapters/ioBroker.kecontact#57]
For some reason my adapter does not connect to the device anymore.
the logfile looks for me ok, I have reinstalled the adapter as well, but still no luck.
What can I do??

thanks in advance,

Martin

**Comment by Sneak-L8** [comment]
Which version?
Please set adapter logging to debug and provide output after restart of adapter.

**Comment by Martin-Stein** [comment]
Hi Volker,

the Version oft he Adapter is v1.3.2, the Host has v3.3.20.
Find attached the desired log-file.
Thanks in advance,

Martin
[IObroker-Log.txt](https://github.com/iobroker-community-adapters/ioBroker.kecontact/files/7611573/IObroker-Log.txt)

**Comment by Sneak-L8** [comment]
Hi Martin,
looks like a problem on your network. It seems that answers from wallbox do not to reach your ioBroker. Is there a firewall in between? Or was UDP disabled in wallbox?
I doubt that it is a problem of the adapter ...

**Comment by Martin-Stein** [comment]
@Sneak-L8 ,
thank you for the hint with the network-connection. My Windows-Computer changed the networkconnection from Private to Public,this has blocked the UDP-Ports. Now it works again!

Thank you, Martin
