### ISSUE TITLE
Keba Wallbox Adapter Vorschlag

### ISSUE THREAD

**Issue by 69paulus** [iobroker-community-adapters/ioBroker.kecontact#83]
Hallo , und danke für diesen Adapter
ich möchte einen Vorschlag machen, da ich nicht ins Netz einspeise, kann ich leider die Regelung der Wallbox nicht einstellen, wäre super nett, wenn es die Möglichkeit gebe, auch nur mit Netz-Bezug zu regulieren(max. Netzbezug bspw. 100 Watt). Ich besitze auch einen Smartfox Energymeter der so eingestellt werden kann, aber  leider die Regelung kann nur in KILOWATT Bereich und nicht in WATT eingestellt werden.
vielen dank 
Viele Grüßen Rassier

**Comment by Sneak-L8** [comment]
Hmm, wäre es nicht das einfachste, wenn Du als surplus die erzeugte Leistung als den Wechselrichter und als regard den Bezug aus den Netz angibst?
Die Differenz wäre dann der Überschuss der PV. Surplus und regard dürfen durchaus gleichzeitig Werte aufweisen

**Comment by 69paulus** [comment]
Hallo Sneak-L8, danke für die schnelle Antwort, ich habe leider nicht so ganz verstanden wie du das beschrieben hast .
Soll ich Scripte erstellen und die datenpunkte (Surplus und Regard ) im Keba Adapter dadurch ändern lassen ?
weil in die Adapter Einstellungen kann ich nichts der Art einstellen.
Datenpunkte von Keba gibt :
regardTimestamp                                   Invalid Date
surplus                                                   (null) W
Bitte beachte das ein Blutiger Anfänger bin :)

Ich hoffe ich stresse nicht zu viel 
vielen dank im voraus

**Comment by Sneak-L8** [comment]
Also wenn Du die Einstellungen der Instanz (nicht unter Objekte) des Adapters aufmachst, dann gibt es dort surplus für den Überschuss und regard für den Netzbezug.
Dort musst Du die Namen der states eintragen, die diese Werte liefern.
Da Du nicht einspeist, wäre surplus immer Null. Damit der Adapter trotzdem weiß, wieviel Strom über ist, solltest Du dort den state eintragen, den z.B. Dein Wechselrichter zur Verfügung stellt. Netzbezug solltest Du von einem energy meter bekommen. Die Differenz ergibt dann den theoretischen Überschuss der dem Adapter zum Laden zur Verfügung steht.
Ist es so verständlicher?

**Comment by 69paulus** [comment]
Hallo, verstehe, also 
Piko hat folgendes:
kostal-piko-ba.0.Power.HouseConsumption
kostal-piko-ba.0.Power.SelfConsumption
Name des States für Netzbezug - Netzbezug (Datenpunkt)
Name des States für Netzeinspeisung - kostal-piko-ba.0.Power.SelfConsumption
Für "Netzbezug"(Datenpunkt =kostal-piko-ba.0.Power.HouseConsumption - kostal-piko-ba.0.Power.SelfConsumption ) musste ich ein script erstellen.
Wäre das so?
Grüße

**Comment by Sneak-L8** [comment]
Kann ich nicht beurteilen. Was steht denn in den beiden States? Und was ist Kostal Piko? Ein Energy Meter? Ein Wechselrichter? Ein anderes Gerät? Vom Namen her sehe ich keinen Unterschied zweischen den States. SelfConsumption könnte auch der Eigenverbrauch von "Kostal Piko" sein. Es braucht einen State in dem steht, wieviel Strom Deine PV gerade erzeugt. Außerdem ein State das irgendwie Rückschlüsse zulässt, wieviel Leistung Du gerade selbst verbrauchst.
Ich kenne Dein System/Deine Geräte nicht, daher kann ich dazu nicht viel sagen.
Da der Adapter aber immer Einspeisung minus Netzbezug rechnet musst Du für diese Differenz keinen einen Datenpunkt erzeugen. Im obigen Beispiel würde SelfComsumption zwei mal abgezogen.

**Comment by 69paulus** [comment]
Also, 
Daten von Wechselrichter : 
PVleistung eigenverbrauch = SelfComsumption
Netzbezug (von mir script erstellt) = HouseConsumption minus SelfComsumption 
Wechselrichter liefert keine daten über Netzbezug, er zeigt zwar, aber nur im Webinterface (macht dasselbe wie ich mit dem Script) aber liefert kein datenpunkt als Netzbezug. 
Und zurück auf deinen Rat am Anfang habe ich alles richtig gemacht oder ? :)
Der Energymeter von Smartfox hat ein schaden zeigt leider in Moment die erzeugte PVleistung nicht, deswegen verwende ich es  die PVleistung vom Wechselrichter 
ob das funktioniert weiss ich noch nicht, das Auto wird nicht geladen ist schon voll :) aber sobald ich getestet habe werde berichten, das es runter reguliert könnte es funktionieren aber ob es hoch reguliert, denke eher nicht , aber mal abwarten , ich lasse ein 100 Watt aus dem Netz zu ziehen und der Wechselrichter Stappelt dann wieder hoch denke ich

**Comment by Sneak-L8** [comment]
Als "PVleistung Eigenverbrauch" klingt für mich nach dem Anteil des von der sonne erzeugtne Stroms den Du selbst verbrauchst.
HouseComsumption hast du nicht erläutert, ist vermutlich die Leistung die vom Hausverbraucht wird unabhängig woher sie kommt (PV-Leistung plus Netzbezug).
Damit gibt es immer noch keine Informationsmöglichkeit über den Überschuss. Der Wechselrichtig sollte doch auch einen Wert "erzeugte PVleistung" liefern, oder?
Auf welchen Rat von mir Du Dich beziehst, kann ich leider nicht erkennen und somit auch nicht bewerten.

**Comment by 69paulus** [comment]
Also Überschuss gibt es bei mir nicht gar nicht, wie ich schon sagte ich speise nicht ein, Stromspeicher habe ich auch nicht , also der Wechselrichter wechselt tatsächlich nur das was gerade verbraucht wird, der PIKO Kostal 10.1 kann das mit zusätzlicher PIKO BA Sensor(Stromwandler), und ist eingestellt auf 100% Selbstverbrauch, deswegen bin ich von Netzbezug abhängig.
der Smartfox macht das problemlos, nur was mich nervt ist das in Smartfox Einstellungen, Netzbezug kann nur  in KW eingestellt werden.
Als ich gesehen habe das Iobroker ein Adapter hat für Keba Wallbox dachte ich yay !!! bei dem Adapter kann ich in Watt einstellen, aber ich habe mich zu früh gefreut denn der Adapter kann nicht nur von Netzbezug regulieren :( ...oder?

**Comment by Sneak-L8** [comment]
Ich weiß, dass Du nicht einspeist, von einem Überschuss im Sinne von Netzeinspeisung habe ich auch nicht redet. Aber wenn Du Deinen Überschuss ins Auto speisen willst, kommen wir um den Begriff nicht herum.
Erst wenn der Adapter weiß, welche Leistung möglich wäre aufgrun der aktuellen Solareinstrahlung kann berechnet werden, wieviel Strom (ohne Netzbezug oder mit einer gewissen Grenze) fürs Laden des Fahrzeugs zur Verfügung steht.
Also: Du brauchst mmer noch einen Datenpunkt, der sagt, wieviel Leistung aktuell möglich wäre. Dann können wir weitermachen.

**Comment by 69paulus** [comment]
man könnte die Helligkeit in Betracht nehmen :) ich kann eventuell ein Datenpunkt erstellen der mir ca. PVleistung vorhersagen kann (ein ca. wert), ich probiere es einfach mal .
Ich weis nicht wie die von Smartfox machen aber es funktioniert, sie haben kein Überschuss 
mal schauen :), melde mich nochmal

**Comment by Sneak-L8** [comment]
Warum vorhersagen? Der Wechselrichter müsste doch wissen, welche Leistung die Module aktuell gerade liefern. Wenn Du nicht ins Netz einspeist, dann muss er ja aktiv herunterregeln. Daher soltle so ein Datenpnukt verfügbar sein. Woher weiß es denn sonst der SmartFox?

**Comment by 69paulus** [comment]
Genau das macht er auch (kostal-piko-ba.0.Power.SelfConsumption), nun ich dachte, du meinst es muss die PVLeistung die zu Verfügung stehen würde wenn eingespeist wird......nun die PV erzeugte Leistung ist ja auch nur die Leistung die auch aktuell verbraucht wird(Beispiel : wenn nur eine Lampe die gerade 100W hat, wird auch nur 100W stehen als SelfConsumption). Smartfox lädt das Auto am Anfang für  ein paar Sekunden mit der Mindeststromstärke zum Starten des Ladevorgangs dann anhand von Netzbezug(1 KW) regelt  Hoch oder Runter

**Comment by 69paulus** [comment]
Heute habe ich es probiert und regelt nicht, entweder werden die Datenpunkte nicht war genommen oder irgendwas falsch konfiguriert. Keine Ahnung 
werden selbst Erzeugte Datenpunkte nicht war genommen?

**Comment by Sneak-L8** [comment]
Doch

**Comment by 69paulus** [comment]
vielleicht muss ich auch noch die Wallbox updaten, gibt eine neue Version. ich melde mich wenn es soweit gebracht habe . danke für die Geduld :) und die Hilfe

**Comment by Sneak-L8** [comment]
Einen Update-Check macht der Adapter für Dich. Wenn eine neue Firmware vorliegt, dann findest Du eine Warning im Log. Also zumidest wenn es sich um eine c-series handelt.

**Comment by 69paulus** [comment]
hat er auch, und es gibt eine neue Version

**Comment by 69paulus** [comment]
der Adapter ist mit der Wallbox verbunden, aber die Wallbox reagiert nicht auf die Adapter Einstellungen

**Comment by Sneak-L8** [comment]
Ich unterstütze ja gerne, aber damit das gut möglich ist, würde ich mehr etwas klarere und ausführlichere Details wünschen. Die Wallbox reagiert nicht auf die Adaptereinstellungen. Das ist der Adapter. Die Wallbox reagiert dann auf die Kommandos des Adapters.

Auf meine Fragen bist auch nicht konkret eingegangen. Es wird weiterhin ein State benötigt, der sagt, wieviel Leistung die PV-Module gerade liefern. Vom Namen her glaubei ch nicht, dass das SelfConsuption ist. Wegen fehlender Netzeinspeisung regelt der Wechselrichter dann herunter und gibt weniger Strom in Dein Netz als die PV-Module aktuell liefern um eine Einspeisung zu verhindern.
Mich würde es wundern, wenn die Anlage diesen Wert nicht kennen würde. Und nochmal: wie komtm der SmartFox an diese Infos? Wenn das bekannt ist, gibt es ja vielleicht noch einen anderen Weg den Überschuss zuberechnen.
Aber solange du mir nicht sagen kannst, wie ich konkret an den möglichen Überschuss der zum Laden des Autos zur Verfügung stehen würde komme, brauchen wir nicht weiter zu disktutieren, was am Adatper einzustellen ist...

**Comment by 69paulus** [comment]
Ich habe einen Screenshot gemacht: Ojekte von Kostal Piko BA Adapter
vielleicht findest du etwas was mir helfen könnte(Morgen früh mach ich ein Screenshot während der Wechselrichter auch am arbeiten ist).

![Screenshot (1)](https://user-images.githubusercontent.com/59329756/156842091-3bfb2a04-daae-489e-ad5a-de27db5864d5.png)

Ich versuche einfach nur irgendwie weniger Strom aus dem Netz zu tanken mehr ist das echt nicht :)
die von Smartfox sagten das, für den Alten EMeter wird wahrscheinlich kein Update mehr geben 
Wenn dir das zu viel stress bereitet, dann muss ich vielleicht ein anderer weg finden um das zu erreichen.
Vielen dank

**Comment by 69paulus** [comment]
Hi , 
ein Screenshot mit dem Wechselrichter im Betrieb 
 Ojekte von Kostal Piko BA Adapter :
![Screenshot (2)](https://user-images.githubusercontent.com/59329756/156883133-d6809cfd-b7a8-4089-aa89-ac32e521c6cb.png)

Kann man gut sehen das da kein Überschuss gibt und auch kein Netzbezug, man kann es rechnen HouseConsuption minus SelfConsumption, dafür habe ich ein Script erstellt . also das was ich brauche ist tatsächlich eine Lösung die nur über Netzbezug  regulieren kann.
ein Screenshot Smartfox webui : 
![Screenshot (3)](https://user-images.githubusercontent.com/59329756/156883283-4337c0cb-9341-4d03-9b3e-b53aa021ac6c.png)

da kann man auch genau sehen das der irgendwie ein schaden hat das er keine PVleistung zeigen kann (wahrscheinlich keine wechsekrichter verbindung) aber regeln auf ein KW  macht er trotzdem, also er regelt nur anhand von Netzbezug

**Comment by 69paulus** [comment]
Smartfox Einstellung screenshot : 
![Screenshot (4)](https://user-images.githubusercontent.com/59329756/156884066-9c4d21fa-809f-451c-b3e0-fc6f0e168a20.png)
da kann man sehen das nur in KW einstellen kann ,ich habe auch mit 0,1 KW probiert, geht nicht, darf kein Komma enthalten 
![Screenshot (5)](https://user-images.githubusercontent.com/59329756/156884138-1dee11d9-5ff4-4720-aebb-3ec4de61afdf.png)
Ich will dich nicht stressen, wenn das nicht geht, dann geht halt nicht. 
Danke trotzdem für zeit und die Mühe.

**Comment by Sneak-L8** [comment]
Danke für die Werte. Damit sieht man doch schon mal viel klarer, welche Werte zur Verfügung stehen. Aber die Namen sind dennoch nicht selbsterklärend. Mich wundert jetzt ein wenig, dass im Smartfox nur kleine (aber im Haushalt übliche Verbrauchswerte von 661W angezeigt werden. Die Werte von diesem Kostal mit 7,1 bzw. 7,4 bzw. 7,8 kW recht hoch sind. Hast Du wirklich einen so hohen Stromverbrauch? Oder wurde da gerade das Auto/ein Batteriespeicher geladen? Wie sehen die Werte von kostal-piko-ba.0.Power aus, wenn Du zwar viel Sonne aber einen geringen Verbrauch hast? Ich glaube, damit sollten wir einen Schritt weiter kommen.

**Comment by 69paulus** [comment]
Hallo , 
Ja, ich glaube war das Auto angeschlossen, aber manchmal sind auch die Elektroheizstäbe (Heizung), manchmal auch die Infrarot Heizpanels. Ich versuche soviel wie möglich solange die Sonne scheint die komplette PVleistung auszunutzen.
Im Smartfox, das was du gesehen hast, ist der Netzbezug (Strommasten), Aber da war tatsächlich das Auto am Laden,  regeln macht der Smartfox sehr gut halt nur in KW Bereich, Netzbezug war zwar nur 661W aber das nur weil den Rest hat die PVAnlage  geliefert, sonst würde da ca 1 KW stehen (alle Verbraucher zusammen + Auto, geregelt wird nur das Laden vom E Auto)

**Comment by 69paulus** [comment]
Bei mir die meisten Geräten werden anhand von Helligkeit an und ausgeschaltet (via Scripts)

**Comment by Sneak-L8** [comment]
Gut, dann würden mich dennoch mal die Werte/State interessieren, wenn die Sonne scheint und einiges an ungenutzem Überschuss bleibt.

**Comment by 69paulus** [comment]
"Wie sehen die Werte von kostal-piko-ba.0.Power aus, wenn Du zwar viel Sonne aber einen geringen Verbrauch hast?"
Tja genau das ist ja auch mein Problem den die Tatsächliche Leistung der PV Anlage bei strahlende Sonne wird nicht angezeigt weil der Wechselrichter wechselt nur den verbrauch, er weißt gar nicht wieviel zu Verfügung steht, es seitdem wird weniger geliefert.

**Comment by 69paulus** [comment]
der Wechselrichter kann eine verbrauchte  Leistung anzeigen, bei Anlagen die ins Netz einspeisen ist einspeisen  wie ein verbrauch, die Leistung gilt als verbraucht

**Comment by 69paulus** [comment]
Stromspannung ist meistens gleich , ändert sich nie , nur die Stromstärke je nach Sonneneinstrahlung

**Comment by 69paulus** [comment]
Ich werde morgen mal schauen die DC Imputs, ob da die volle Leistung der PV Anlage angezeigt wird,  oder nur das was verbraucht wird.

**Comment by 69paulus** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/59329756/157321209-260f59cd-b437-4a5c-a3de-6d5e1cc26f4f.png)

**Comment by 69paulus** [comment]
Hallo,
also zeigt immer noch nur das was gerade verbraucht wird
![Screenshot (6)](https://user-images.githubusercontent.com/59329756/157402927-a63b7bc3-68eb-44b1-b1d3-29452e8ab0e9.png)
Rechts Habpanel Eigenverbrauch Links Iobroker Objekte Kostal, DC Input1+DC Input2, oder "Solar DC" von System bereits zusammen gerechnet

**Comment by Sneak-L8** [comment]
Tja, aber irgendwoher muss ich die Info bekommen, wieviel Leistung zur Verfügung steht. Da es der SmartFox kann, muss es wohl so einen Wert geben. Wenn Du den findest, können wir weitersehen. Aber ohne den kann der Adpater nichts ausruchten. Das ist kein Problem des Adapters sondern der zur Verfügung stehenden Informationen.

**Comment by 69paulus** [comment]
Der Smartfox bekommt diese Info nicht, er bekommt die selben Datenpunkte wie auch der Kostal Piko Ba adapter liefert .
wie ich mal gesagt habe ich habe ein PVleistung(Aktuelle Virtuelle PVLeistung) datenpunkt erstellt abhängig von Helligkeit, und Überschuss kann gerechnet habe Aktuelle PVleistung minus Selfcomsumption dan ergibt das was man braucht, oder ?

**Comment by Sneak-L8** [comment]
Aber wie soll der Smartfox die Steuerung machen, wenn er nicht weiß wieviel PV-Leistung zur Verfügung steht? er hat ja keine Glaskugel.

Aber wenn Du einen Datenpunkt hast, der angibt, wieviel Leistung (möglicher PV-Überschuss) zur Verfügung steht, dann trage den in den Einstellungen des KeContact-Adapters bei surplus ein. Dann sollte es mit dem Laden klappen.

**Comment by 69paulus** [comment]
Außerdem der Smartfox hat keine Verbindung zum Wechselrichter, das habe ich mal erwähnt. die kommunizieren nicht miteinander

**Comment by Sneak-L8** [comment]
Ja, die einstellungen scheinen so richtig zu sein. Die Einheiten stehen bei jeder Einstellung (unter dem Strich) mit dabei.
Ich habe mir das aber nochmal überlegt. Deine Beschreibung erscheint schlüssig. Der Smartfox "testet" eine etwas höhere Ladeleistung und wenn sie zu hoch ist (Natzbezug > 1kW) regelt er entsprechend runter.
Aber eins passt nicht. Wenn du z.B. 2 kW von der PV-Anlage bekommst und selbst 1,5 kW verbrauchst. Dann blieben 1,5 kW fürs Auto. Das reicht natürlich nicht, weil selbstm it 1 Phase mind. 1,4 kW gezogen werden. Dann müsste der Smartfox ja immer wieder einen Ladevorgang mit 6A testweise starten um zu sehen, ob so viel Leistung vorhanden ist.
Jedes Mal würde also ein Ladevorgang kurz starten. Also z.B. alle 5 Minuten, was bedeutet, das er "nur" alle 5 Minuten nachregelt, aber dass "schon" nach nur 5 Minuten immer wieder ein Ladevorgang gestartet wird. Das mag kein Auto und würde jedes Mal unnötig viel Netzleistung ziehen. Rund um die Uhr. Auch nachts .... er hat ja keine Info, wann die Sonne scheint wie Du schreibst. Das halte ich nicht für eine machbare Stategie.
Ich sehe weiterhin nicht das Problem beim KeContact-Adapter sondern bei der fehlenden Datenlage Deines Systems.

**Comment by 69paulus** [comment]
Da der Smartfox nicht mehr mit dem Wechselrichter kommuniziert, startet gar nicht mehr, muss ich immer entweder mehr vom Netzt abziehen lassen, oder über die Nacht einfach die Automatik aus, oder 7 KW vom Netz erlauben, also geht schon wenn man selbst Manuel einstellt, die Einstellung um mehr von der PVanlage zu nützen ist meist tagsüber und natürlich wenn auch die Sonne scheint. Ich dachte das der KeContact Adapter würde genauso wie der Smartfox regeln den mit demm Smartfox funktioniert nur halt in KW Bereich

**Comment by Sneak-L8** [comment]
Sorry, aber Du schreibst etwas unklar für mich. Kannst Du das anders beschreiben?
Ich verstehe: 
- der SmartFox kann von sich aus gar keinen Ladevorgang starten, da musst Du erst manuell etwas anstoßen
- Du musst selbst nachts die automatik ausschalten
- "Einstellubng um mehr von der PV-Energie zu nutzen" - wer stellt da was ein? Der SmartFox? Du?

Du erwartest, dass der KeContact-Adapter genauso regelt wie der SmartFox. Aber eine klare Beschreibung, was der SmartFox nun wirklich tut, habe ich bisher noch nicht herausgelesen.

Die von mir im Post zuvor beschriebenen Probleme scheinen sich in Deiner letzten Antwort eher zu bestätigen. Da ist keine Automatik, die in Deiner Umgebung (im Gegensatz zu Anlegen mit Einspeisung) einen Ladevorgang bei genügend Sonne startet oder regelt.
Daher ist mir weiterhin unklar, was (und vor allem wie) der Adapter diese Automatik leisten soll, ohne mit bekannte ausreichende Informationen zur Datenlage.

**Comment by 69paulus** [comment]
Also,
Den Ladevorgang startet der Smartfox von sich aus nicht.
Der Smartfox regelt allein nur vom Netzbezug abhängig, er kommuniziert leider nicht mehr mit dem Wechselrichter, hat aber an sonnigen Tagen keinen Einfluss, was er nicht macht ist, den Ladevorgang neu zu starten 
Ganz einfach : 
Netzbezug höher als 1 KW regelt er die Ladeleistung runter 
Netzbezug niedriger als 1 KW regelt er die Ladeleistung hoch bis 1 KW Netzbezug erreicht wird
Aber nur solange der Netzbezug nicht  höher als eingestellt ist,  wenn aber, dass doch der Fall ist, stoppt er den Ladevorgang und startet nicht mehr neu.
Ich muss  dann wieder den Schalter X1 betätigen, aus und nochmal an machen, um das ganze wieder ins Laufen zu bringen.
Dass der Ladevorgang stoppt, macht mir nichts aus, natürlich wäre es super, wenn er von alleine wieder starten würde, aber da ich nichts ins Netz einspeise und auch kein Stromspeicher habe, wird das auch nie möglich sein.
Wenn ich das Auto doch laden will, egal ob die  PV Anlage genug Leistung zur Verfügung stellt oder nicht, schalte ich die Automatik aus oder stelle Netzbezug auf einen höheren  Wert ein, sodass die Ladung nicht unterbrochen wird.
Mein Wunsch ist nur, dass Netzbezug Regelung im Watt Bereich möglich ist und nicht in KW (weil ich dachte, dass der Kecontact Adapter auf die selbe Art und Weise wie der Smartfox manager regelt)
Ich will auch nicht, dass du dir soviel Stress damit machst, und es tut mir echt leid, dass du wegen mir soviel Zeit investieren musstest, dafür danke ich dir.
Die meisten Leuten, die eine PV Anlage haben, speisen ins Netz ein, und somit haben sie auch keine Probleme damit in dieser Richtung.
Ich werde mit virtuelle Werte (selbst erstellte Datenpunkte) den KeContact Adapter zu konfigurieren, wenn es funktioniert, schön :) wenn nicht dann habe ich  halt Pech gehabt.
Danke nochmal

**Comment by 69paulus** [comment]
Hallo , 
ich wollte nur mal sagen das seid ich mit **Virtuellen Überschuss** (via Script) eingestellt habe und mein Energymeter aus dem Netzwerk raus geholt habe, funktioniert der Adapter super , regelt hoch und runter , startet und stoppt die Wallbox wie es sein soll
danke nochmal :)
