### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Ytnom2404** [iobroker-community-adapters/ioBroker.kecontact#94]
Hallo,

kann mir bitte jemand die Regard und Surplus Werte erklären. Ich denke ich habe alle möglichen Werte in meine Kostal Plenticore Anlage, nur habe ich keinen Plan was genau welcher Wert anzeigen soll.

Ich habe bisher nur versucht unter Surplus den Power to grid wert zu nutzen (zeugt von 0 bis xxxWatt) an wieviel Strom ich verkaufe.

Gruß
Monty

**Comment by Sneak-L8** [comment]
Hallo Monty,

surplus = Überschuss, den Du ins Netz einspeist
regard = Bezug aus dem öffentlichen Stromnetz

Deine PV erzeugt gerade 800W und Du verbrauchst 200W => surplus = 600, regard = 0
Deine PV erzeugt gerade 10W und Du verbrauchst 300W => surplus = 0, regard = 290

Falls Dein Kostal Plenticore beides in einem State speichert (surplus > 0 und redard < 0 oder umgekehrt), dann musst Du nur diesen State in den Adapter-Einstellungen der Keba eintragen.

**Comment by Ytnom2404** [comment]
Super … danke.

mich werde die Werte gleich mal einstellen.

:-)

Danke für die schnelle Antwort.
Mit freundlichen Grüßen
Monty

**Comment by Ytnom2404** [comment]
Ich muss noch einmal etwas fragen.

die beiden Werte sind klar aber leider  habe ich noch einen BYD Speicher der so unsichtbar Strom liefert, da ich ja keinen Strom kaufe und der Wert des Strombezugs ja null bleibt in dem Moment. Kann man da etwas machen?

**Comment by Ytnom2404** [comment]
Habe ich nun genauso gemacht. Ich habe eine neue variable angelegt die die Summe aus beiden Werten ist. Gekaufter Strom + Akkustrom. Somit sollte er es nun berücksichtigen.

Danke.

wäre auch ein cooles Feature für die nächste Version … einfach ein Feld für den Akkustrom.

**Comment by Sneak-L8** [comment]
Bzgl. Feature: da bin ich mir nicht sicher. Manche möchten vielleicht auch den Akkustrom zum Laden nutzen, andere eher nicht. Und passt das, einfach die Werte zu addieren? Da fehltm ir einfach die Erfahrung. Sollte vielleicht einen Akku kaufen :-)

**Comment by Ytnom2404** [comment]
Jepp so einfach ist es … entweder man nimmt nur den gekauften Strom … lässt den zweiten Wert weg. Dann wird der Akkustrom nicht eingerechnet und der Akku wird genutzt. Wenn der Speicherstrom zusätzlich eingetragen wird , wird er addiert , da er ja auch als gekaufter Strom über eine andere Quelle . kommt. So hätten es alle selbst in der Hand…entweder zweiten wert eintragen oder nicht. 
Gruß Monty

**Comment by Sneak-L8** [comment]
Ok, wenn es so einfach ist, dann kann ich einen weiteren State für den Batteriespeicher vorsehen.
Der Batteriespeicher lädt => Leistung zum surplus hinzurechnen
Der Batteriespeicher gibt Leistung ab => Leistung zum regard dazuzählen
Jetzt bin ich mir unsicher, ob die States bei allen Batteriespeichern gleich sind, also ob es immer ein State ist und ob das Laden der Batterie ein postiver, das Entladen ein negativer Wert ist oder umgekehrt.
Daher würde ich evtl. einfach zwei States anlegen, so wie bei surplus und regard und die Werte dann entspr. addieren.
Denkst du, das passt? Dann würde ich das in den nächsten Tage angehen und bräuchte dich als Tester... :)

**Comment by Ytnom2404** [comment]
Bin dabei…

irgendwie glaube ich aber , dass man nur einmal den Wert hinzufügen muss, weil mein Surplus verkaufter Strom ja eh immer nur anfängt wenn der Speicher 100% voll ist. Nur beim Laden des Autos muss er auch aufpassen dass er den Strom vom Speicher sieht und nicht da anfängt Strom zu nutzen. Stimmt doch oder… 

somit kann man sauber kontrollieren ob man den Speicher entladen will zum Laden des Autos.

btw. Warum zeigt er bei mir nie den PV Charging text an? Hast du eine Idee?

**Comment by Ytnom2404** [comment]
Ach … und kann man den State nicht auch per drop down Liste auswählen?

**Comment by Sneak-L8** [comment]
Mangels Erfahrung leider alles nur Annahmen: Dein Speicher dürfte die Leistungsaufnahme anhand des Überschusses am Netzübergabepunkt/EnergyMeter ermitteln. Wenn Dein auto anfängt zu laden, dann sollte er nachrangig sein und somit seine Leistungsaufnahme reduzieren bzw. einstellen bzw. sogar Leistung abgeben.
Wenn ich die Leistungsabgabe des Speichers als State angebe und damit in die Berechnung einfließen lasse, dann würde das Auto auch mit Strom aus dem Akkuspeicher geladen. Das Problem ist, dass der aber ja nur Leistung abgibt, wenn sie auch irgendwo bezogen wird. Solange ich das Auto lade, gibt er auch keine Leistung ab, wird also nicht berechnet. D.h. man bräuchte noch die Info, welche Leistung der Akkuspeicher derzeit maximal liefern kann. Wenn diese "mögliche Leistung" automatisch (bis auf 0 absinkt) sinkt, wenn der Akku leerer wird, dann wäre genau dieser Wert anzugeben. Das dürfte dann ziemlich sicher ein extra State sein. es geht ja um die theoretische maximal verfügbare Leistung des Speichers.
Sonst addiere ich die beiden Werte (EnergyMeter und Speicherleistungsaufnahme), da einer der beiden dann ja immer null sein dürfte. Da der Akkuspeicher ja auch nur eine begrenzte Aufnahmeleistung hat, könnte die auch mal unter der Leistung der PV-Anlage liegen. Dann wäre zusätlzich auch surplus positiv und es ist richtig diese zu addieren.
Ob eine DropDown-Liste für die States geht, kläre ich ab. Hab ich bisher auch bei keinem anderen Adapter gesehen...

**Comment by Ytnom2404** [comment]
Ich schaue mir morgen mal an wie der Wagen lädt und ob alles funktioniert. Ich bin mir grad nicht sicher :-)



Von meinem iPhone gesendet

**Comment by Ytnom2404** [comment]
Hallo Volker,

Ich habe gestern und heute noch etwas abgewartet. Meine neue Variable mit der Summe aus gekauften Strom und Speicherstrom funktioniert. Verkaufter Strom bleibt unverändert.

So nebenbei habe ich gelesen dass der minimale Ladestrom einphasig immer 6A ist. Bei mir jedenfalls ist es so.

Willst Du die Updates angehen?

Gruß
Monty 

Von meinem iPhone gesendet

**Comment by Sneak-L8** [comment]
Hallo Monty, ja, 6A ist bei den meisten Fahrzeugen das Minimum, egal ob 1-, 2- oder 3-phasig.
Dann mache ich mich mal an die Arbeit. Kann abern icht sagen, wie schnell ich bin :-)

**Comment by Ytnom2404** [comment]
Super… Danke 

Von meinem iPhone gesendet

**Comment by Ytnom2404** [comment]
Hallo,

Hört sich gut an… wie kann ich die Version updaten?

Gruß 
Monty

Von meinem iPhone gesendet

**Comment by Sneak-L8** [comment]
Einfach im ioBroker auf Experteneinstellung (das Symbol mit der Motorradhaube) und dann das Katzensymbol. Dort das Register git auswählen und im Feld "kec" tippen, dann sollte KeContact-Adapter angeboten werden.

**Comment by Ytnom2404** [comment]
Installiert… teste wenn die Sonne mal wieder scheint..

Anbei ein Foto wo bei mir der Text nach der Auswahl nicht sauber aussieht.

Gruß
Monty 

Von meinem iPhone gesendet

**Comment by Ytnom2404** [comment]
Moin….

Irgendwie hatte ich mit dem neuen Wert einen Fehler .

Der ist für die Speicher Aufnahme? 

Meine Variable war ja Stromeinkauf vom Netzprovider + Speicher Strom Abgabe, damit der Speicher nicht entladen wird und das Auto rein über die Solaranlage lädt.

Bitte erkläre mir noch einmal was genau der neue Feldwert des Speichers macht… hört sich ja anders an „Leistungsaufnahme des Speichers“

Gruß
Monty

Von meinem iPhone gesendet

**Comment by Sneak-L8** [comment]
Leider war bem vorletzten Post kein Bild dabei...
Die Stromabgabe wäre ja dann im Netzbezug einzurechnen. Den würde ich im ersten Schritt wie beschrieben noch nicht einberechnen.
Zunächst ist ja wichtig, wieviel Leistung der speicher gerade aufnimmt.
Beipiel:
- PV-Anlage liefert 6.000W
- Verbrauchen ziehen gerade 1.000W
- Stromseicher lädt mit 2.500W
- EnergyMeter an Netzabschluss würde eine Einspeisung von 2.500W anzeigen (6.000W - 2.500W - 1.000W).
Der Adapter würde mit 2.500W bei einem 3-phasigen Fahrzeug nicht laden.
Wird nun die aktuelle Ladeleistung des Batteriespeichers einbezogen (Überschuss 2.500W + Speicher 2.500W) = 5.000W würde der Adapter nun mit dem Laden beginnen. Der Speicher würde dann pausieren, weil PV-Leistung 6.000W minus Hausstrom 1.000W und minus Auto 5000W = 0W.

**Comment by Sneak-L8** [comment]
Bei git ist jetzt ne neue Version, wo Stromaufnahme und -abgabe aus einem Speicher auch als getrente States unterstützt werden (siehe auch 2. open issue hier)
